name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: ci   # 👈 espera a que termine 'ci'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: railway link 45d7692c-f270-4954-83b7-1f24cbde9e61
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --ci --service e912d1f3-8797-4ee9-a842-2b6e6aaca6a4
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
