name: CI/CD - Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test --if-present

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
