name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Jest globally
        run: npm install -g jest

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service e912d1f3-8797-4ee9-a842-2b6e6aaca6a4
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
