name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Railway
        uses: railway/actions/deploy@v1
        with:
          service: e912d1f3-8797-4ee9-a842-2b6e6aaca6a4
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
