name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test --if-present

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: ci
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: e912d1f3-8797-4ee9-a842-2b6e6aaca6a4
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Railway Login
        run: railway login --token $RAILWAY_TOKEN --ci

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}
