name: CI/CD - Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # Descomenta si quieres ejecutar tests
      # - name: Run tests
      #   run: npm test --if-present

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI v3.14.0
        run: npm install -g @railway/cli@3.14.0

      - name: Set Railway token
        run: echo $RAILWAY_TOKEN > ~/.railway/token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Link Railway Project
        run: railway link --project e912d1f3-8797-4ee9-a842-2b6e6aaca6a4

      - name: Deploy to Railway
        run: railway up
